[01]
path = "10-out-of-10.webp"
caption = "Bochen sitting in the loaf position, 10 out of 10 points."
source = "Instagram @bochen_the_cat"
[02]
path = "bochen-gaming.webp"
caption = "Bochen accompanying Linde while gaming."
source = "Instagram @bochen_the_cat"
[03]
path = "bochen-vs-michael.webp"
caption = "Bochen vs [Michael HT](@/w/michael-ht.md), a fan's edit of the image advertising [Crane](@/w/jacob-crane.md) vs [Queen](@/w/gabriel-queen.md) for [PpW Ale Grzeje](@/e/ppw/2024-07-13-ppw-ale-grzeje.md)."
source = "Michael HT"
[04]
path = "bochen-bochening.jpg"
caption = "Bochen being his Bochen-y self."
source = "zrzutka.pl"
[05]
path = "bochen-walczy-z-choroba.jpg"
caption = '"Epic battle of Grey Loaf and the Illness" - a painting put up for auction.'
source = "zrzutka.pl"
[06]
path = "the-mysteries-of-bochen.jpg"
caption = '"The Mysteries of Bochen" - a painting put up for auction.'
source = "zrzutka.pl"
[07]
path = "i-believe-in-bochen.jpg"
caption = '"I Believe in Bochen" T-shirt.'
source = "zrzutka.pl"
[08]
path = "paczam.jpg"
caption = "Bochen marvelling at the world."
source = "zrzutka.pl"
[09]
path = "they-re-the-same-picture.jpg"
caption = "The real Bochen with a plushie Bochen available through the support website."
source = "zrzutka.pl"
[10]
path = "strona.webp"
caption = "A screenshot of the crowdfunding website. The update beneath the picture announces the passing of the furry fella."
source = "zrzutka.pl"
skip_art = true
