01 = { path = "spontaneity.webp", caption = "&quot;Fans&quot; &quot;spontaneously&quot; cheering for NQW.", source = "Private archives" }
02 = { path = "widac-nie-widac.webp", caption = "The Bush Position.", source = "Private archives" }
03 = { path = "lj-blade-wejscie.webp", caption = "LJ Blade.", source = "Private archives" }
04 = { path = "ring-announcer.webp", caption = "Kaja, the ring announcer.", source = "Private archives" }
05 = { path = "barry-1.webp", caption = "LJ Blade's tag-team partner, Barry Matt.", source = "Private archives" }
06 = { path = "suicide.webp", caption = "Suicide.", source = "Private archives" }
07 = { path = "kermit.webp", caption = "Suicide's tag-team partner, Kermit.", source = "Private archives" }
08 = { path = "enzuigiri.webp", caption = "LJ Blade hits Suicide with an Enzuigiri worthy of Antonio Inoki.", source = "Private archives" }
09 = { path = "not-half-bad-suplex.webp", caption = "Suicide delivers a Vertical Suplex to LJ Blade.", source = "Private archives" }
10 = { path = "oversell.webp", caption = "LJ Blade oversells Suicide's cutter.", source = "Private archives" }
11 = { path = "kermit-deathlock.webp", caption = "Barry Matt applies a Sharpshooter to Kermit.", source = "Private archives" }
12 = { path = "drivepiler.webp", caption = "LJ Blade's botched Pilvedriver on Suicide.", source = "Private archives" }
13 = { path = "swan1000kg.webp", caption = "Suicide performs a Swanton Bomb from a ladder onto LJ Blade.", source = "Private archives" }
14 = { path = "barry-2.webp", caption = "Barry Matt's second entrance.", source = "Private archives" }
15 = { path = "froggy.webp", caption = "Froggy's second entrance.", source = "Private archives" }
16 = { path = "nie-ma.webp", caption = "Barry Matt launches himself at the empty mattress.", source = "Private archives" }
17 = { path = "best-view-in-the-house.webp", caption = "A new fan from the neighbourhood.", source = "Private archives" }
18 = { path = "suplex-village.webp", caption = "LJ Blade holds Suicide in a Delayed Vertical Suplex.", source = "Private archives" }
19 = { path = "prog-flash.webp", caption = "LJ Blade in a Frog Splash from the ladder.", source = "Private archives" }
20 = { path = "knife-mcstabberson.webp", caption = "LJ Blade approves of the stabbing maniac.", source = "Private archives" }
21 = { path = "cross-body-worthy-of-jesus.webp", caption = "Suicide delivers a Crossbody from the ladder to LJ Blade.", source = "Private archives" }
22 = { path = "smoke-attack.webp", caption = "An audience member blows smoke at Suicide.", source = "Private archives" }
23 = { path = "very-pro-very-ladder.webp", caption = "A Spinning 360 Whatchamacallit from the ladder.", source = "Private archives" }
24 = { path = "general-kenobi.webp", caption = "Hello there!", source = "Private archives" }
25 = { path = "stabbity-stab-stab-stab.webp", caption = "Suicide via plastic cutlery.", source = "Private archives" }
26 = { path = "a-fan-is-born.webp", caption = "The girl from the neighbourhood clasps hands with LJ Blade.", source = "Private archives" }
