# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "PSW"

theme = "anemone"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[slugify]
paths_keep_dates = true

[extra]
# Put all your custom variables here

list_pages = false
default_theme = "dark"
header_nav = [
  { url = "/about", name_en = "about" }
]