# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml"]

title = "TPW" # Teczki Polskiego Wrestlingu. In English, Tales of Polish Wrestling

theme = "web"

taxonomies = [
  { name = "chronology", render = false },
  { name = "venue", render = false },
  { name = "same-venue", render = false },
  { name = "chrono_root", render = false },
  { name = "country", render = false },
  { name = "category", render = false },
]

[search]
index_format = "elasticlunr_json"

[slugify]
paths_keep_dates = true

[extra]
# Put all your custom variables here
new_issue_url = "https://github.com/k3rni/teczki-polskiego-wrestlingu/issues/new"

# Display matchfinder links next to unlinked names in roster pages
mf_links_in_roster = true
# This will be used as the link to matchfinder for a specific talent, %s substituted with their name
mf_link_format = "//mf.tpwres.pl?q=%s"
# Venues that have embedded geography info will link to this
carto_link_format = "//carto.tpwres.pl#%s"

list_pages = false
default_theme = "dark"
header_links = [
  { path = "@/e/_index.md", name = "Events", icon = "calendar-1" },
  { path = "@/o/_index.md", name = "Orgs", icon = "handshake" },
  { path = "@/w/_index.md", name = "People", icon = "users" },
  { path = "@/tt/_index.md", name = "Teams", icon = "biceps-flexed" },
  { path = "@/a/_index.md", name = "Articles", icon = "book" },
  { path = "@/v/_index.md", name = "Places", icon = "map-pin-house" },
  { path = "@/c/_index.md", name = "Championships", icon = "trophy" },
  { url = "//mf.tpwres.pl", name = "Matchfinder", icon = "crosshair" },
  { url = "//art.tpwres.pl", name = "Artwall", icon = "image-play" },
  { url = "//carto.tpwres.pl", name = "Carto", icon = "map" }
]

footer_links = [
  { path = "@/about.md", name = "About", icon = "info"},
  { path = "@/a/contributing.md", name = "Contributing", icon = "file-pen-line"},
  { url = "//github.com/tpwres/teczki-polskiego-wrestlingu", name = "GitHub", icon = "github"},
  { url = "/atom.xml", name = "Atom Feed", icon = "rss"},
  { path = "@/recent-changes.md", name = "Recent Changes", icon = "file-diff" },
  { path = "@/authors.md", name = "Authors", icon = "heart" }
]
mensch_theme = "theme-base-0e"

gallery_root = "/i"

tts_root = "//unalengua.com/ipa-translate?hl=en&ttsLocale=pl-PL&sl=pl&ttsMode=sentence&speed=3&voiceId=Maja"

# These orgs are excluded from the talentlists
special_orgs = [
  "splat"
]

[extra.org_styles.ppw]
bg = '#5b007e'
text_fg = '#c7c7c7'

[extra.org_styles.mzw]
bg = '#208315'
text_fg = '#ffffff'

[extra.org_styles.kpw]
bg = '#133762'
text_fg = '#ffffff'

[extra.org_styles.ddw]
bg = '#71171f'
text_fg = '#fbf1c7'

[extra.org_styles.tbw]
bg = '#000'
text_fg = '#999a93'

[extra.org_styles.dfw]
bg = '#a9100b'
text_fg = '#fbf1c7'

[extra.org_styles.ptw]
bg = '#000'
text_fg = '#ffffff'

[extra.org_styles.twf]
bg = '#4f8ebf'
text_fg = '#ffffff'

[extra.chronology]
arena = "KPW Arena"
backyardmania = "Backyardmania"
beer-expo = "Poznań Beer Expo"
godzina-zero = "KPW Godzina Zero"
international = "International"
ledwo-legalne = "Ledwo Legalne"
oldtown = "OldTown Festival"
poznan-fair = "Poznań International Fair"
project-basement = "Project Basement"
pyrkon = "Pyrkon"
ryucon = "Ryucon"
stocznia-gdanska = "Stocznia Gdańska"
underground = "PTW Underground"
