0000 = { path = "kpw-arena-31-plakat-alt.webp", caption = "Official poster, featuring [Krystian Malinowski](@/w/krystian-malinowski.md).", source = "kpwrestling.pl / Official KPW Facebook" }
0001 = { path = "kpw-arena-31-plakat.webp", caption = "Original version of the poster, featuring [Zefir](@/w/zefir.md) prior to his firing from KPW.", source = "kpwrestling.pl / Official KPW Facebook" }
0002 = { path = "kpw-arena-31-plakat-alt-2.jpg", caption = "Alternative poster, featuring [Eryk Lesak](@/w/eryk-lesak.md).", source = "ErykLesak @ Facebook" }
0003 = { path = "lom-ratuffa.webp", caption = "Image announcing Tom LaRuffa.", source = "Official KPW Facebook" }
0004 = { path = "filip-fux-vs-tomczak.webp", caption = "Image announcing [Filip Fux](@/w/filip-fux.md) vs [Tomczak](@/w/tomczak.md).", source = "Official KPW Facebook" }
0005 = { path = "greg-vs-chemik.webp", caption = "Image announcing [Greg](@/w/greg.md) vs [Chemik](@/w/chemik.md).", source = "Official KPW Facebook" }
0006 = { path = "hans-vs-tom.webp", caption = "Image announcing [Hans Schulte](@/w/hans-schulte.md) vs Tom LaRuffa.", source = "Official KPW Facebook" }
0007 = { path = "leon-lato.webp", caption = "Image announcing [Leon Lato](@/w/leon-lato.md).", source = "Official KPW Facebook" }
0008 = { path = "paskalesak.webp", caption = "Image announcing Markus Paskal vs [Eryk Lesak](@/w/eryk-lesak.md).", source = "Official KPW Facebook" }
0009 = { path = "wyszechrady.webp", caption = "Image announcing [Lukáš Mottl](@/w/skull-evil.md) & [David Oliwa](@/w/david-oliwa.md).", source = "Official KPW Facebook" }
0010 = { path = "michal-fux-vs-ron-corvus.webp", caption = "Image announcing [Michał Fux](@/w/michal-fux.md) vs [Ron Corvus](@/w/ron-corvus.md).", source = "Official KPW Facebook" }

0101 = { path = "kinga.webp", caption = "[Kinga Miotke](@/w/kinga-miotke.md) opens the show.", source = "M3n747" }
0102 = { path = "suddenly-krzeslo.webp", caption = "Filip Fux emerges from underneath the ring to strike Tomczak in the back with a chair.", source = "M3n747" }
0103 = { path = "suddenly-malinowski.webp", caption = "[Krystian Malinowski](@/w/krystian-malinowski.md) changes the plans.", source = "M3n747" }
0104 = { path = "suddenly-adepci.webp", caption = "Tomczak gets back on his feet, while Rookies Two, Three and One are instructed by Krystian Malinowski to remove Filip Fux from the ring.", source = "M3n747" }

2001 = { path = "lukaszowi-skapnelo-mistrzostwo.webp", caption = "[David Oliwa](@/w/david-oliwa.md) and [Lukáš Mottl](@/w/skull-evil.md).", source = "M3n747" }
2002 = { path = "i-point-at-rookie-two-is-my-finger-not-rookie-two-himself.webp", caption = "[David Oliwa](@/w/david-oliwa.md) and [Lukáš Mottl](@/w/skull-evil.md) mock Rookie Two.", source = "Tomek O." }
2003 = { path = "od-stop-po-piety-wszedl-napiety-mordercze-na-nim-instrumenty.webp", caption = "More guys, more undies!", source = "M3n747" }
2004 = { path = "miecz-swietny.webp", caption = "[Rookie One](@/w/rookie-one.md) fends off David Oliwa and [Lukáš Mottl](@/w/skull-evil.md) with a kendo stick.", source = "M3n747" }
2005 = { path = "lato-z-jedynka.webp", caption = "[Leon Lato](@/w/leon-lato.md) takes the side of [Rookie One](@/w/rookie-one.md). In the background is [Krystian Czekaj](@/w/krystian-czekaj.md).", source = "M3n747" }
2006 = { path = "technicznie-rzecz-biorac-liczy-sie-jako-pin.webp", caption = "[David Oliwa](@/w/david-oliwa.md) pins [Rookie One](@/w/rookie-one.md), counted by Krystian Czekaj. In the corners stand Leon Lato and [Lukáš Mottl](@/w/skull-evil.md).", source = "M3n747" }
2007 = { path = "sneaky-oliwa.webp", caption = "David Oliwa sneaks up on Leon Lato.", source = "M3n747" }
2008 = { path = "wyszechrady-wygraly.webp", caption = "[David Oliwa](@/w/david-oliwa.md) and [Lukáš Mottl](@/w/skull-evil.md) celebrate their victory. In the background, referee [Krystian Czekaj](@/w/krystian-czekaj.md) appears to be contemplating his life choices.", source = "M3n747" }

3001 = { path = "sedzia-w-cieniu-lesaka.webp", caption = "[Eryk Lesak's](@/w/eryk-lesak.md) entrance.", source = "M3n747" }
3002 = { path = "alan-ale-nie-delon.webp", caption = "Sędzia Alan.", source = "M3n747" }
3003 = { path = "markus-paskal.webp", caption = "Markus Paskal's entrance.", source = "M3n747" }
3004 = { path = "lesak-po-weekendowym-kursie-chiropraktyki.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) holds Markus Paskal's head in an iron grip, as Sędzia Alan oversees the action.", source = "M3n747" }
3005 = { path = "bardzo-duzo-niutonow-na-metr-kwadratowy.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) torments Markus Paskal, while [Chemik](@/w/chemik.md) delivers a promo. In front of the ring stands Paskal's mother.", source = "M3n747" }
3006 = { path = "z-ta-pania-lepiej-nie-zadzierac.webp", caption = "[Eryk Lesak](@/w/eryk-lesak.md) and [Chemik](@/w/chemik.md) attempt to intimidate Paskal's mother, without much success.", source = "M3n747" }

4001 = { path = "aleksander-the-awesome.webp", caption = "[Kamil Aleksander](@/w/kamil-aleksander.md) returns to KPW.", source = "M3n747" }

5001 = { path = "tomczak-wchodzi.webp", caption = "Tomczak's entrance.", source = "Tomek O." }
5002 = { path = "filip-siedzi.webp", caption = "[Filip Fux](@/w/filip-fux.md) relaxes in a chair, while downed Tomczak wraps a length of steel chain around his fist. In the background stands [Krystian Czekaj](@/w/krystian-czekaj.md).", source = "M3n747" }
5003 = { path = "bez-tego-bedzie-bolalo.webp", caption = "Protective padding removed from a turnbuckle by Tomczak.", source = "M3n747" }
5004 = { path = "nie-ma-tego-wiec-boli.webp", caption = "Tomczak pushes [Filip Fux](@/w/filip-fux.md) into the exposed turnbuckle. Note David Oliwa's hat on the corner post.", source = "M3n747" }
5005 = { path = "przylancuszyl-mu-jak-jolop-aleksowi.webp", caption = "Tomczak, moments after felling Filip Fux with a chain-assisted punch.", source = "M3n747" }
5006 = { path = "two-metres-of-victory.webp", caption = "[Tomczak](@/w/tomczak.md) victorious.", source = "Tomek O." }
5007 = { path = "fewer-metres-of-defeat.webp", caption = "Bloodied [Filip Fux](@/w/filip-fux.md).", source = "M3n747" }



6001 = { path = ".webp", caption = ".", source = "M3n747" }
7001 = { path = ".webp", caption = ".", source = "M3n747" }
8001 = { path = ".webp", caption = ".", source = "M3n747" }





9001 = { path = ".webp", caption = ".", source = "Tomek O." }
