[001]
path = "2024-11-16-ptw-underground-24-plakat.webp"
caption = 'Official poster. Pictured left to right, top row: [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Miyagi Shida](@/w/miyagi-shida.md), ["Starboy" Nano Lopez](@/w/nano-lopez.md), [Max Speed](@/w/max-speed.md), [Alex Brave](@/w/alex-brave.md); middle row: [Spartan](@/w/spartan.md), Jack Vaughn, [Dawid "Puncher" Seńko](@/w/puncher.md), Aaron Williams, Jake Omen; bottom row: [Arkadiusz Pawłowski](@/w/pan-pawlowski.md), [Łukasz "Prezes" Okoński](@/w/lukasz-okonski.md).'
source = "Official PTW Facebook"
[002]
path = "nano-lopez-vs-jake-omen.webp"
caption = "Image announcing [Nano Lopez](@/w/nano-lopez.md) vs Jake Omen."
source = "Official PTW Facebook"
[003]
path = "spartan-vs-aaron-williams.webp"
caption = "Image announcing [Spartan](@/w/spartan.md) vs Aaron Williams."
source = "Official PTW Facebook"
[004]
path = "alex-brave-vincent-caravaggio-vs-max-speed-miyagi-shida.webp"
caption = "Image announcing [Alex Brave](@/w/alex-brave.md) & [Vincent Caravaggio](@/w/vincent-caravaggio.md) vs [Max Speed](@/w/max-speed.md) & [Miyagi Shida](@/w/miyagi-shida.md)."
source = "Official PTW Facebook"
[005]
path = "jack-vaughn-vs-puncher.webp"
caption = "Image announcing Jack Vaughn vs Puncher."
source = "Official PTW Facebook"
[006]
path = "newt-nova-vs-rust.webp"
caption = "Image announcing [Newt Nova](@/w/newt-nova.md) vs [Rust](@/w/rust.md)."
source = "Official PTW Facebook"
[007]
path = "luca-bjorn-vs-serg-sullivan.webp"
caption = "Image announcing [Luca Bjorn](@/w/luca-bjorn.md) vs [Serg Sullivan](@/w/serg-sullivan.md)."
source = "Official PTW Facebook"
