[01]
path = "totalna-anihilacja-plakat.webp"
caption = """\
    Official poster. Left to right, top: 
    [CJ Klakson](@/w/cj-klakson.md), [Sigma Boy xD](@/w/sigma-boy.md), [Łukasz Okoński](@/w/lukasz-okonski.md), [Spartan](@/w/spartan.md), [Daniel Razor](@/w/daniel-razor.md);
    bottom: 
    [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Nano Lopez](@/w/nano-lopez.md), [Arkadiusz Pawłowski](@/w/pan-pawlowski.md), [Alex Brave](@/w/alex-brave.md), [Puncher](@/w/puncher.md).
"""
source = "Official PTW Facebook"

[02]
path = "klakson-vs-caravaggio.webp"
caption = "Image announcing [CJ Klakson](@/w/cj-klakson.md) vs [Vincent Caravaggio](@/w/vincent-caravaggio.md)"
source = "Official PTW Facebook"
