[01]
path = "halloweenowa-rozpierducha-plakat.webp"
caption = """\
    Official poster. Left to right, top: 
    [Nano Lopez](@/w/nano-lopez.md), [Łukasz Okoński](@/w/lukasz-okonski.md) [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Arkadiusz Pawłowski](@/w/pan-pawlowski.md);
    bottom: 
    [Sigma Boy xD](@/w/sigma-boy.md), [Spartan](@/w/spartan.md), [Alex Brave](@/w/alex-brave.md), [Puncher](@/w/puncher.md).
"""
source = "Official PTW Facebook"

[02]
path = "daniel-razor-open-challenge.webp"
caption = 'Image announcing [Daniel Razor's](@/w/daniel-razor.md) Open Challenge.'
source = "Official PTW Facebook"
