[01]
path = "swiat-nie-bedzie-plakat.webp"
caption = """\
    Official poster. Top to bottom, left to right: 
    [Łukasz Okoński](@/w/lukasz-okonski.md), [CJ Klakson](@/w/cj-klakson.md), [Diana Strong](@/w/diana-strong.md);
    [Daniel Razor](@/w/daniel-razor.md), [Miyagi Shida](@/w/miyagi-shida.md);
    [Spartan](@/w/spartan.md);
    [Polski Niedźwiedź](@/w/polski-niedzwiedz.md), [Sigma Boy xD](@/w/sigma-boy.md);
    [Nano Lopez](@/w/nano-lopez.md);
    [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Damian Lambert](damien-rothschild.md);
    [Alex Brave](@/w/alex-brave.md), [Puncher](@/w/puncher.md);
    [Arkadiusz Pawłowski](@/w/pan-pawlowski.md), Damian Adler.
"""
source = "Official PTW Facebook"

[02]
path = "oh-baby-baby-how-was-i-supposed-to-know.webp"
caption = "Image announcing [Puncher](@/w/puncher.md) vs [Spartan](@/w/spartan.md)."
source = "Official PTW Facebook"
