[01]
path = "halloweenowa-rozpierducha-plakat.webp"
caption = """\
    Official poster. Left to right, top: 
    [Nano Lopez](@/w/nano-lopez.md), [Łukasz Okoński](@/w/lukasz-okonski.md) [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Arkadiusz Pawłowski](@/w/pan-pawlowski.md);
    bottom: 
    [Sigma Boy xD](@/w/sigma-boy.md), [Spartan](@/w/spartan.md), [Alex Brave](@/w/alex-brave.md), [Puncher](@/w/puncher.md).
"""
source = "Official PTW Facebook"

[02]
path = "daniel-razor-open-challenge.webp"
caption = "Image announcing [Daniel Razor's](@/w/daniel-razor.md) Open Challenge."
source = "Official PTW Facebook"

[03]
path = "karate-misiek.webp"
caption = "Image announcing [Miyagi Shida](@/w/miyagi-shida.md) vs [Polski Niedźwiedź](@/w/polski-niedzwiedz.md)."
source = "Official PTW Facebook"

[04]
path = "tu-nacisnac-i-wtedy-zatrabi.webp"
caption = "Image announcing [CJ Klakson](@/w/cj-klakson.md)."
source = "Official PTW Facebook"

[05]
path = "andi-zickzack-vs-nic-wesker.webp"
caption = "Image announcing Andi ZickZack vs Nic Wesker."
source = "Official PTW Facebook"

[06]
path = "sawicki-wraca.webp"
caption = "Image announcing [Sawicki](@/w/sawicki.md)."
source = "Official PTW Facebook"

[07]
path = "international-showcase.webp"
caption = "Image announcing Kenny B. & M.R.D. vs Ivan Sanzio & Davide Adami."
source = "Official PTW Facebook"

[08]
path = "main-event.webp"
caption = "Image announcing Team Okoński vs Nietykalni. Clockwise from top, left: [Łukasz Okoński](@/w/lukasz-okonski.md), [Nano Lopez](@/w/nano-lopez.md), [Spartan](@/w/spartan.md), [Sigma Boy xD](@/w/sigma-boy.md); right: [Arkadiusz Pawłowski](@/w/pan-pawlowski.md), [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Puncher](@/w/puncher.md), [Alex Brave](@/w/alex-brave.md)."
source = "Official PTW Facebook"
