[01]
path = "totalna-anihilacja-plakat.webp"
caption = """\
    Official poster. Left to right, top: 
    [CJ Klakson](@/w/cj-klakson.md), [Sigma Boy xD](@/w/sigma-boy.md), [Łukasz Okoński](@/w/lukasz-okonski.md), [Spartan](@/w/spartan.md), [Daniel Razor](@/w/daniel-razor.md);
    bottom: 
    [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Nano Lopez](@/w/nano-lopez.md), [Arkadiusz Pawłowski](@/w/pan-pawlowski.md), [Alex Brave](@/w/alex-brave.md), [Puncher](@/w/puncher.md).
"""
source = "Official PTW Facebook"

[02]
path = "klakson-vs-caravaggio.webp"
caption = "Image announcing [CJ Klakson](@/w/cj-klakson.md) vs [Vincent Caravaggio](@/w/vincent-caravaggio.md)."
source = "Official PTW Facebook"

[03]
path = "lopez-vs-razor.webp"
caption = "Image announcing [Nano Lopez](@/w/nano-lopez.md) vs [Daniel Razor](@/w/daniel-razor.md)."
source = "Official PTW Facebook"

[04]
path = "alex-brave-show.webp"
caption = "Image announcing The [Brave](@/w/alex-brave.md) Show."
source = "Official PTW Facebook"

[05]
path = "shida-vs-fabio.webp"
caption = "Image announcing [Miyagi Shida](@/w/miyagi-shida.md) vs Fabio Romano"
source = "Official PTW Facebook"
