[01]
path = "ptw-apokalipsa-plakat.webp"
caption = """\
Official poster. At the top, looming over the others is [Krampus](@/w/krampus.md);
left to right, top row: [Damian Lambert](@/w/damian-lambert.md), [Sigma Boy xD](@/w/sigma-boy.md), [Alex Brave](@/w/alex-brave.md), [Vincent Caravaggio](@/w/vincent-caravaggio.md), [Nano Lopez](@/w/nano-lopez.md), [Sędzia Herno](@/w/sedzia-herno.md), [Sędzia Klaudiusz](@/w/sedzia-klaudiusz.md), [Daniel Razor](@/w/daniel-razor.md), [Polski Niedźwiedź](@/w/polski-niedzwiedz.md); 
bottom row: [Arkadiusz Pawłowski](@/w/pan-pawlowski.md), [Puncher](@/w/puncher.md), [Miyagi Shida](@/w/miyagi-shida.md), [Diana Strong](@/w/diana-strong.md), [Serg Sullivan](@/w/serg-sullivan.md), [Spartan](@/w/spartan.md), [Łukasz Okoński](@/w/lukasz-okonski.md).
"""
source = "Official PTW Facebook"

[02]
path = "shida-vs-serg.webp"
caption = "Image announcing [Miyagi Shida](@/w/miyagi-shida.md) vs [Serg Sullivan](@/w/serg-sullivan.md) in a Casket Match."
source = "Official PTW Facebook"

[03]
path = "guerilla-vs-equus.webp"
caption = "Image announcing [Alex Brave](@/w/alex-brave.md) & [Vincent Caravaggio](@/w/vincent-caravaggio.md) vs [Sędzia Herno](@/w/sedzia-herno.md) & [Sędzia Klaudiusz](@/w/sedzia-klaudiusz.md)."
source = "Official PTW Facebook"

[04]
path = "puncher-vs-diana.webp"
caption = "Image announcing [Puncher](@/w/puncher.md) vs [Diana Strong](@/w/diana-strong.md)."
source = "Official PTW Facebook"

[05]
path = "krampus.webp"
caption = "Image announcing [Krampus](@/w/krampus.md)."
source = "Official PTW Facebook"
