[01]
path = "bol-istnienia-plakat.webp"
caption = """\
    Official poster. Clockwise, from the top: [Puncher](@/w/puncher.md), [Miyagi Shida](@/w/miyagi-shida.md), [Daniel Razor](@/w/daniel-razor.md),
    [El G](@/w/el-g.md), [Diana Strong](@/w/diana-strong.md), [Nano Lopez](@/w/nano-lopez.md),
    [Spartan](@/w/spartan.md), [Sigma Boy xD](@/w/sigma-boy.md), [Alex Brave](@/w/alex-brave.md).
"""
source = "Official PTW Facebook"

[02]
path = "puncher-vs-lambert.webp"
caption = 'Image announcing [Dawid "Puncher" Se≈Ñko](@/w/puncher.md) vs [Damian Lambert](@/w/damien-rothschild.md).'
source = "Official PTW Facebook"

[03]
path = "nano-bedzie.webp"
caption = 'Image announcing ["Starboy" Nano Lopez](@/w/nano-lopez.md) in action.'
source = "Official PTW Facebook"
