01 = { path = "neomania-3-logo.jpg", caption = "Official logo.", source = "Official PpW YouTube" }
02 = { path = "sin-cara-moonsaults-on-mystic-tiger.jpg", caption = "Sin Cara moonsaults on Mystic Tiger.", source = "Official PpW YouTube" }
03 = { path = "mister-z-z-trzeciej-hustawki.jpg", caption = "[Mister Z](@/w/mister-z.md) on top of the playground swing.", source = "Official PpW YouTube" }
04 = { path = "interview-2-vins.jpg", caption = "[Johnny Blade](@/w/johnny-blade.md) interviewed by...", source = "Official PpW YouTube" }
05 = { path = "interview-1-blade.jpg", caption = "â€¦[himself]](@/w/johnny-blade.md).", source = "Official PpW YouTube" }
06 = { path = "pro-ring.jpg", caption = "Garden variety wrestling ring.", source = "Official PpW YouTube" }
