01 = { path = "hades-yt-belt.jpg", caption = "[Hades](@/w/olgierd.md) with the PpW YouTube Championship.", source = "Official PpW YouTube" }
02 = { path = "match-1.jpg", caption = "[Jim Enerico](@/w/mister-z.md) vs [Snake](@/w/snake.md).", source = "Official PpW YouTube" }
03 = { path = "match-2.jpg", caption = "[KAT](@/w/biesiad.md) & [Psychodela](@/w/psychodela.md) vs Kote≈Ç & Krasso.", source = "Official PpW YouTube" }
04 = { path = "match-3.jpg", caption = "[Hades](@/w/olgierd.md) vs Jake Young.", source = "Official PpW YouTube" }
05 = { path = "dont-try-this-at-home-or-at-all.jpg", caption = "[A fan](@/w/snake.md) exhibiting self-destructive tendencies.", source = "Official PpW YouTube" }
06 = { path = "flaming-sword-of-great-justice.jpg", caption = "The flaming sword of Hades.", source = "Official PpW YouTube" }
