001 = { path = "wjazd-na-rewir-plakat.webp", caption = "Official poster featuring [Justin Joy](@/w/justin-joy.md), [Mister Z](@/w/mister-z.md), [Biesiad Strong](@/w/biesiad.md) and [Goblin](@/w/goblin.md).", source = "Official PpW Facebook" }
002 = { path = "wjazd-na-rewir-plakat-alt.webp", caption = "Alternate poster.", source = "Official PpW Facebook" }
003 = { path = "justin-joy-wraca.webp", caption = "Image announcing [Justin Joy](@/w/justin-joy.md).", source = "Official PpW Facebook" }
004 = { path = "kwasowy-cieśla.webp", caption = "Image announcing [Biesiad Strong](@/w/biesiad.md) vs [Goblin](@/w/goblin.md).", source = "Official PpW Facebook" }
005 = { path = "lis-bedzie-platal-na-oceanie-cienia.webp", caption = "Image announcing Antoni Ocean & [Shadow](@/w/shadow.md) vs [Axel Fox](@/w/axel-fox.md) & [Bartosz Plata](@/w/plata.md).", source = "Official PpW Facebook" }
006 = { path = "gustav-gryffin-gauntlet-match.webp", caption = "Image announcing [Gustav Gryffin](@/w/gustav-gryffin.md).", source = "Official PpW Facebook" }
007 = { path = "blada-agatka.webp", caption = "Image announcing [Agentka Agatka](@/w/agentka-agatka.md) vs [Johnny Blade](@/w/johnny-blade.md).", source = "Official PpW Facebook" }
008 = { path = "justin-i-queen-vs-vic-i-oskar.webp", caption = "Image announcing [Justin Joy](@/w/justin-joy.md) & [Gabriel Queen](@/w/gabriel-queen.md) vs [Vic Golden](@/w/vic-golden.md) & [Oskar Alexander](@/w/oskar-alexander.md).", source = "Official PpW Facebook" }
009 = { path = "zet-oglasza-tymy-palcymy.webp", caption = "[Mister Z's](@/w/mister-z.md) very big announcement.", source = "Official PpW Facebook" }

101 = { path = "co-to-moze-byc-i-dlaczego-pasy.webp", caption = "A table with mysterious object(s) covered with black cloth.", source = "M3n747" }
102 = { path = "niespodziewanka.webp", caption = "[Michael HT](@/w/michael-ht.md) with the unveiled [PpW Tag Team Championship](@/c/ppw-tag-team-championship.md) belts.", source = "M3n747" }

201 = { path = "drapu-drapu.webp", caption = "[Axel Fox](@/w/axel-fox.md).", source = "M3n747" }
202 = { path = "platting.webp", caption = "Antoni Ocean surfing on the back of Bartosz Plata.", source = "M3n747" }
203 = { path = "shadow-i-fox.webp", caption = "[Shadow](@/w/shadow.md) faces [Axel Fox](@/w/axel-fox.md), refereed by [Sędzia Seweryn](@/w/sedzia-seweryn.md). On the apron stands Bartosz Plata.", source = "M3n747" }
204 = { path = "nad-ocean-tamtedy.webp", caption = "[Shadow](@/w/shadow.md) points at the downed Antoni Ocean.", source = "M3n747" }
205 = { path = "cieniste-wody.webp", caption = "[Shadow](@/w/shadow.md) and Antoni Ocean emerge victorious, as declared by [Sędzia Seweryn](@/w/sedzia-seweryn.md).", source = "M3n747" }

301 = { path = "wez-20-dag-tego-i-zamieszaj-frajerze.webp", caption = "[Johnny Blade](@/w/johnny-blade.md) with a crutch and a baking tray, flipped off by Agentka Agatka.", source = "M3n747" }
302 = { path = "jeszcze-nie-koniec.webp", caption = "Oskar Alexander pulls Agentka Agatka out of the way of [Johnny Blade](@/w/johnny-blade.md) and his 'END' road sign. Far to the left stands [Sędzia Kornel](@/w/sedzia-kornel.md).", source = "M3n747" }
303 = { path = "a-po-co-komu-kark.webp", caption = "Agentka Agatka hits a Back-to-Belly Piledriver on Johnny Blade, to the apparent horror and disbelief of Sędzia Kornel.", source = "M3n747" }
304 = { path = "gwiazdy-przed-oczami.webp", caption = "[Agentka Agatka](@/w/agentka-agatka.md) parades Johnny Blade with a photo stapled to his face in front of the crowd.", source = "M3n747" }
305 = { path = "foto-1.webp", caption = "Agentka Agatka grabs hold of the photo of Robert Star…", source = "M3n747" }
306 = { path = "foto-2.webp", caption = "…and rips it off.", source = "M3n747" }
307 = { path = "if-it-bleeds-we-can-pin-it.webp", caption = "Bloodied Johnny Blade outside of the ring.", source = "M3n747" }
308 = { path = "foto-3.webp", caption = "The photo with Johnny Blade's blood after the match.", source = "M3n747" }
309 = { path = "prosto-z-wieliczki.webp", caption = "The salt that closely encountered Johnny Blade's open wounds.", source = "M3n747" }




400 = { path = ".webp", caption = ".", source = "M3n747" }
500 = { path = ".webp", caption = ".", source = "M3n747" }
600 = { path = ".webp", caption = ".", source = "M3n747" }
700 = { path = ".webp", caption = ".", source = "M3n747" }
800 = { path = ".webp", caption = ".", source = "M3n747" }
900 = { path = ".webp", caption = ".", source = "M3n747" }
