0001 = { path = "hardcore-friday-turniej-typeshit-plakat.webp", caption = "Official poster, featuring [Olgierd](@/w/olgierd.md), [Biesiad Strong](@/w/biesiad.md) and [Michael HT](@/w/michael-ht.md).", source = "Official PpW Facebook" }
0002 = { path = "legia-vs-hardkory.webp", caption = "Image announcing [Legia Łysych](@/tt/legia-lysych.md) ([Olgierd](@/w/olgierd.md) & [Marco Hammers](@/w/marco-hammers.md)) vs The Hardcores ([Johnny Blade](@/w/johnny-blade.md) & [Biesiad](@/w/biesiad.md)).", source = "Official PpW Facebook" }
0003 = { path = "oskar-vs-queen-bullrope.webp", caption = "Image announcing [Oskar Alexander](@/w/oskar-alexander.md) vs [Gabriel Queen](@/w/gabriel-queen.md) in a Bullrope Match.", source = "Official PpW Facebook" }
0004 = { path = "fox-vs-vic.webp", caption = "Image announcing [Axel Fox](@/w/jakub.md) vs [Vic Golden](@/w/vic-golden.md) in a Chairs Match.", source = "Official PpW Facebook" }
0005 = { path = "gobliniak.webp", caption = "Image announcing [Goblin](@/w/goblin.md) vs [Stanisław Van Dobroniak](@/w/stanislaw-van-dobroniak.md).", source = "Official PpW Facebook" }
0006 = { path = "luchadoresz.webp", caption = "Image announcing the return of [Wonder Haze](@/w/wonder-haze.md) and [Sentinel](@/w/sentinel.md).", source = "Official PpW Facebook" }
[9999]
path = "alt-poster.webp"
caption = """\
Alternative poster/promo image.
In the top row: Agentka Agatka, Gustav Gryffin, Biesiad, Marco Hammers.
Middle row: Oskar Alexander and Sambor's legs, then headless Johnny Blade and Olgierd, and Goblin.
Bottom row: Mister Z with his briefcase, and Johnny Blade again in a dog collar.
All the photos are from [Turniej TypeShit](@/e/ppw/2025-07-05-ppw-turniej-typeshit.md).
"""
source = "Official PpW Facebook"
