001 = { path = "ppw-duch-swiat-smak-krwi.webp", caption = "Official poster featuring [Santa Biesiad](@/w/biesiad.md). In the bottom-left corner are the faces of Akane Fujita and Shigehiro Irie.", source = "Official PpW Facebook" }
