001 = { path = "ppw-jednak-hardcore-plakat.webp", caption = "Official poster, featuring [Olgierd](@/w/olgierd.md). The caption says: _It was supposed to be indieâ€¦ [but it's] hardcore after all_.", source = "Official PpW Facebook" }
