001 = { path = "ppw-teraz-albo-nigdy-2-zapowiedz.webp", caption = "Announcement image.", source = "Official PpW Facebook" }
002 = { path = "wiecej-typa-wiecej-broni.webp", caption = "Image announcing the main event.", source = "Official PpW Facebook" }
