[01]
path = "rafi-exit-insta.jpg"
caption = "Screenshot of [Rafi](@/w/rafi.md)'s goodbye post. His instagram profile is currently (June 2024) set to private."
source = "Instagram @rafirarytaswrestling"
skip_art = true

[02]
path = "sambor-insta-thanks.jpg"
caption = "[Sambor](@/w/sambor.md) thanking the fans, organization and Pawłowski for support. The text states that his time in wrestling is not over, and his story will be told in many taverns."

[03]
path = "boro-au-revoir.png"
caption = "Au revoir, from Boro's Last Dance Instagram Story'"
source = "Instagram @borogng"
skip_art = true

[04]
path = "dziedzic-goodbye.jpg"
caption = "[Dziedzic](@/w/dziedzic.md)'s farewell post on Instagram."
source = "Instagram @dziedzicwrestling"

[05]
path = "sinister-farewell-insta.jpg"
caption = "[Sinister](@/w/sinister.md) thanking everyone in his farewell post."
source = "Instagram @sinister_wrestler"

[06]
path = "sinister-farewell-text.png"
caption = "Full text from Sinister's farewell post."
source = "Instagram @sinister_wrestling"
skip_art = true

[07]
path = "ptw_dismissal.jpg"
caption = "PTW firing Jacob Crane in August 2022."

[08]
path = "owczy-ped.jpg"
caption = "[Puncher's](@/w/puncher.md) comic titled 'Herd Instinct', comparing the talent quitting PTW to sheep heading into a pig's anus (referring to [PpW](@/o/ppw.md))"
source = "Facebook @PTWpuncher"

[09]
path = "leak-puncher-fox.png"
caption = "[Puncher](@/w/puncher.md) leaking info about Axel Fox's possible exit in a discussion thread on the House Of Wrestling Facebook group."
source = "Facebook HouseOfWrestling"
skip_art = true

[10]
path = "paterek-tweet.jpg"
caption = "Arek Paterek's tweet signing out of the commentary desk."
source = "Twitter @APaterek"

[11]
path = "paterek-o-baliku.png"
caption = "Paterek mentioning that Balik also quit PTW."
source = "Twitter @APaterek"
skip_art = true

[12]
path = "paterek-o-pawlowskim.png"
caption = "Paterek criticizing Pawłowski for not responding to his farewell message, among other things."
source = "Twitter @APaterek"
skip_art = true

[13]
path = "sewi-exit.jpg"
caption = "[Ref Seweryn](@/w/sedzia-seweryn.md)'s farewell story on Instagram."
source = "Instagram @sewi_the_ref"

[14]
path = "boro-ptw-last-dance-1.jpg"
caption = "[Boro](@/w/boro.md) at a PTW event, from his Last Dance Instagram Story"
source = "Instagram @borogng"

[15]
path = "boro-ptw-last-dance-2.jpg"
caption = """\
MZW wrestlers [Queen](@/w/gabriel-queen.md), [Crane](@/w/jacob-crane.md), [Fox](@/w/jakub.md),
[Isnorr](@/w/isnorr.md), [Madman Charlie](@/w/madman-charlie.md), [Rafael Kid](@/w/rafael-kid.md),
[Aron Wake](@/w/aron-wake.md) (as Pikachu), [Olgierd](@/w/olgierd.md) and others,
from Boro's Last Dance Instagram story. Bottom text says 'The message is clear'.
"""
source = "Instagram @borogng"

[16]
path = "boro-ptw-last-dance-3.jpg"
caption = "[Boro](@/w/boro.md), [Taras](@/w/taras.md) and [Disco Pablo](@/w/disco-pablo.md) from Boro's Last Dance Instagram Story"
source = "Instagram @borogng"

[17]
path = "boro-ptw-last-dance-4.jpg"
caption = "MZW wrestlers holding a Dave Batista poster and a banner. The first visible word on the banner is [Zieloni](@/tt/zieloni.md) (_The Greens_), from Boro's Last Dance Instagram Story"
source = "Instagram @borogng"

[18]
path = "mutant-stare-smieci.jpg"
caption = 'Instagram story by Michał "Mutant" Świątkowski, polling the followers where should he continue training wrestling.'
source = "Instagram @mutant_wrestler"
skip_art = true

[19]
path = "mutant-hammers.jpg"
caption = 'Michał "Mutant" Świątkowski taking a selfie with [Marco Hammers](@/w/marco-hammers.md) backstage at [Ledwo Legalne IV](@/e/ppw/2024-06-08-ppw-ledwo-legalne-4.md)'
source = "Instagram @mutant_wrestler"
