11 = { path = "tjw-01.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
12 = { path = "tjw-02.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
13 = { path = "tjw-03.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
14 = { path = "tjw-04.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
15 = { path = "tjw-05.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
16 = { path = "tjw-06.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
19 = { path = "tjw-99-lesak.webp", caption = "Lesak's signature, before being crossed out.", source = "M3n747", skip_art = true }
21 = { path = "tjw-ii-01.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
22 = { path = "tjw-ii-02.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
23 = { path = "tjw-ii-03.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
24 = { path = "tjw-ii-04.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
25 = { path = "tjw-ii-05.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
26 = { path = "tjw-ii-06.webp", caption = "Signatures.", source = "M3n747", skip_art = true }
