[01]
path = "supertv-19940114-dsf.webp"
caption = "TV listing for DSF on Friday, 14.01.1994."
source = "archive.org [super-tv-3-94](https://archive.org/details/super-tv-3-94)."
skip_art = true

[02]
path = "dziennik-baltycki-19940527-ring-wolny.webp"
caption = "TV listing for DSF on Friday, 27.05.1994.<br />_&quot;Free Ring&quot;: male wrestling (WCW)_."
source = "[Dziennik Bałycki #122]([Dziennik Bałycki #122](https://www.bibliotekacyfrowa.eu/dlibra/publication/56643/edition/55712), page 7/14."
skip_art = true

[03]
path = "teletydzien-19990118-tnt.webp"
caption = "TV listing for TNT on Friday, 22.01.1999, poorly cropped. The wrestler shown is Big Van Vader."
source = "archive.org [tele-tydzien-nr-5-18.01.1999-skan_20220929](https://archive.org/details/tele-tydzien-nr-4-18.01.1999-skan_20220929), page 17/63."
skip_art = true

[04]
path = "teletydzien-19990118-dsf.webp"
caption = "TV listing for DSF on Saturday, 23.01.1999."
source = "archive.org [tele-tydzien-nr-5-18.01.1999-skan_20220929](https://archive.org/details/tele-tydzien-nr-4-18.01.1999-skan_20220929), page 23/63."
skip_art = true

[05]
path = "nazi-spine.jpg"
caption = "Example of machine-translated subtitles in an NJPW show, aired on 25.05.2025:<br/>_Oh no no no no_<br/>_Did not take this Nazi spine_"
source = "Extreme Sports Channel"
skip_art = true
