001 = { path = "zlote-ewenementy-2025.jpg", caption = "Announcement of the inaugural 2025 awards.", source = "Official PpW Facebook"}
101 = { path = "ze-2025-wrestler-roku.webp", caption = "Golden Ewenements 2025.<br/>Wrestler of the Year.", source = "Official PpW Facebook"}
102 = { path = "ze-2025-walka-roku.webp", caption = "Golden Ewenements 2025.<br/>Match of the Year.", source = "Official PpW Facebook"}
103 = { path = "ze-2025-moment-roku.webp", caption = "Golden Ewenements 2025.<br/>Moment of the Year.", source = "Official PpW Facebook"}
104 = { path = "ze-2025-debiut-roku.webp", caption = "Golden Ewenements 2025.<br/>Newcomer of the Year.", source = "Official PpW Facebook"}
105 = { path = "ze-2025-plakat-roku.webp", caption = "Golden Ewenements 2025.<br/>Best Show Poster.", source = "Official PpW Facebook"}
