01 = { path = "2026-01-17-wwe-road-to-royal-rumble.jpg", caption = "Graphic announcing the tour dates.", source = "WWE.com" }
02 = { path = "wwe-registration.webp", caption = "Registration form.", source = "WWE.com" }
03 = { path = "kodymil-rodewski.webp", caption = "Cody Rhodes's tour dates.", source = "CodyRhodes @ Twitter" }
04 = { path = "ciekawe-czy-umie-stroic-wiolonczele.jpg", caption = "Bronson Reed's tour dates.", source = "BRONSONISHERE @ Twitter" }
