001 = { path = "2026-01-17-wwe-road-to-royal-rumble.jpg", caption = "Graphic announcing the tour dates.", source = "WWE.com" }
002 = { path = "wwe-registration.webp", caption = "Registration form.", source = "WWE.com" }
003 = { path = "kodymil-rodewski.webp", caption = "Cody Rhodes's tour dates.", source = "CodyRhodes @ Twitter" }
004 = { path = "ciekawe-czy-umie-stroic-wiolonczele.jpg", caption = "Bronson Reed's tour dates.", source = "BRONSONISHERE @ Twitter" }

101 = { path = "luctor-ergo-sum.webp", caption = "Outside view of the venue.", source = "M3n747" }
102 = { path = "sum-ergo-tak-zwany-olimpijczyk.webp", caption = "Inside the venue.", source = "M3n747" }

201 = { path = "jevon-evans.webp", caption = "Je'Von Evans.", source = "M3n747" }
202 = { path = "cm-punk.webp", caption = "CM Punk.", source = "M3n747" }
203 = { path = "bayley.webp", caption = "Bayley with Lyra Valkyria.", source = "M3n747" }
204 = { path = "raquel-rodriguez.webp", caption = "Raquel Rodriguez.", source = "M3n747" }

205 = { path = "", caption = ".", source = "M3n747" }

206 = { path = "", caption = ".", source = "M3n747" }
207 = { path = "", caption = ".", source = "M3n747" }
208 = { path = "", caption = ".", source = "M3n747" }
209 = { path = "", caption = ".", source = "M3n747" }
210 = { path = "", caption = ".", source = "M3n747" }
