[01]
path = "2023-03-11-mzw-game-on-plakat.jpg"
caption = "Official poster. Wrestlers pictured, top to bottom: Rubix, [Dieter Schwartz](@/w/dieter-schwartz.md), [Matt Buckna](@/w/matt-buckna.md), [Shadow](@/w/shadow.md), Denim Adams."
source = "Official MZW Facebook"

[02]
path = "chris-x-vs-rubix.webp"
caption = "Image announcing [Chris X](@/w/chris-x.md) vs Rubix."
source = "Official MZW Facebook"

[03]
path = "dieter-schwartz-vs-denim-adams.webp"
caption = "Image announcing [Dieter Schwartz](@/w/dieter-schwartz.md) vs Denim Adams."
source = "Official MZW Facebook"

[04]
path = "matt-buckna-vs-alex-arthur.webp"
caption = "Image announcing [Matt Buckna](@/w/matt-buckna.md) vs [Alex Arthur](@/w/alex-arthur.md)."
source = "Official MZW Facebook"

[05]
path = "leo-zayde-vs-michael-payne-vs-alex-ace.webp"
caption = "Image announcing Leo Zayde vs Michael Payne vs [Alex Ace](@/w/alex-ace.md)."
source = "Official MZW Facebook"

[06]
path = "zeritus-vs-shadow.webp"
caption = "Image announcing [Zeritus](@/w/zeritus.md) vs [Shadow](@/w/shadow.md)."
source = "Official MZW Facebook"
