01 = { path = "ddw-aon-01.jpg", caption = "Jędruś Bułecka's theme performed live.", source = "Jędruś Bułecka @ Facebook", skip_art = true }
02 = { path = "ddw-aon-02.jpg", caption = "[Jędruś Bułecka's](@/w/jedrus-bulecka.md) entrance.", source = "Jędruś Bułecka @ Facebook" }
03 = { path = "ddw-aon-03.jpg", caption = "[Jędruś Bułecka's](@/w/jedrus-bulecka.md) entrance.", source = "Jędruś Bułecka @ Facebook" }
04 = { path = "ddw-aon-04.jpg", caption = "[Jędruś Bułecka's](@/w/jedrus-bulecka.md) entrance.", source = "Jędruś Bułecka @ Facebook" }
05 = { path = "ddw-aon-05.jpg", caption = "[Jędruś Bułecka's](@/w/jedrus-bulecka.md) entrance.", source = "Jędruś Bułecka @ Facebook" }
06 = { path = "ddw-aon-06.jpg", caption = "Battle royal.", source = "Jędruś Bułecka @ Facebook" }
07 = { path = "ddw-aon-07.jpg", caption = "Battle royal.", source = "Jędruś Bułecka @ Facebook" }
08 = { path = "ddw-aon-08.jpg", caption = "[Jędruś Bułecka](@/w/jedrus-bulecka.md) outside of the ring.", source = "Jędruś Bułecka @ Facebook" }
09 = { path = "ddw-aon-09.jpg", caption = "Battle royal.", source = "Jędruś Bułecka @ Facebook" }
10 = { path = "ddw-aon-10.jpg", caption = "Battle royal.", source = "Jędruś Bułecka @ Facebook" }
11 = { path = "ddw-aon-11.jpg", caption = "[Jędruś Bułecka](@/w/jedrus-bulecka.md) with fans after the show.", source = "Jędruś Bułecka @ Facebook" }
12 = { path = "ddw-aon-12.jpg", caption = "[Jędruś Bułecka](@/w/jedrus-bulecka.md) with fans after the show.", source = "Jędruś Bułecka @ Facebook" }
13 = { path = "ddw-aon-13.jpg", caption = "[Jędruś Bułecka](@/w/jedrus-bulecka.md) signing an autograph after the show.", source = "Jędruś Bułecka @ Facebook" }



20 = { path = "10-man-battle-royal-rules.webp", caption = "The rules of the 10 Man Battle Royal.", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
20 = { path = ".webp", caption = ".", source = "Jędruś Bułecka's private archives" }
